blog/urls.py
from django.urls import path
from . import views
from .views import AllSaveView, PostListView, PostDetailView, PostCreateView, PostUpdateView, PostDeleteView, SaveView, UserPostListView, LikeView,LikeCommentView, posts_of_following_profiles,  AllLikeView

urlpatterns = [
    path('', views.first, name='firsthome'),
    path('home/', PostListView.as_view(), name='blog-home'),
    path('feed/', posts_of_following_profiles, name='posts-follow-view'),
    path('post/user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>/', PostDetailView, name='post-detail'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/like/', LikeView, name='post-like'),
    path('liked-posts/', AllLikeView, name='all-like'),
    path('post/save/', SaveView, name='post-save'),
    path('saved-posts/', AllSaveView, name='all-save'),
    path('post/comment/like/', LikeCommentView, name='comment-like'),
    path('about/', views.about, name='blog-about'),
    path('search/', views.search, name='search'),
]

myproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),

    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
    
    path('accounts/', include('allauth.urls')),
    
    path('', include('blog.urls')),
    path('user/', include('users.urls')),
    path('notifications/', include('notification.urls')),
    path('chats/', include('chat.urls')),
    path('vc/', include('videocall.urls')),
    path('friend/', include('friend.urls', namespace='friend')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notification/urls.py
from django.urls import path
from notification.views import ShowNotifications

urlpatterns = [
    path('', ShowNotifications, name='show-notifications'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from ckeditor.fields import RichTextField

""" Post model """
class Post(models.Model):
    title = models.CharField(max_length=150)
    content = RichTextField(blank=True, null=True)
    date_posted = models.DateTimeField(default=timezone.now)
    date_updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name="blogpost", blank=True)
    saves = models.ManyToManyField(User, related_name="blogsave", blank=True)

    def total_likes(self):
        return self.likes.count()

    def total_saves(self):
        return self.saves.count()

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk":self.pk})


""" Comment model """
class Comment(models.Model):
    post = models.ForeignKey(Post, related_name="comments" , on_delete=models.CASCADE)
    name = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    likes = models.ManyToManyField(User, related_name="blogcomment", blank=True)
    reply = models.ForeignKey('self', null=True, related_name="replies", on_delete=models.CASCADE)

    def total_clikes(self):
        return self.likes.count()

    def __str__(self):
        return '%s - %s - %s' %(self.post.title, self.name, self.id)

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={"pk":self.pk})

blog/forms.py
from django import forms
from django.forms import fields, widgets
from .models import Post, Comment

class CommentForm(forms.ModelForm):
    body = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control custom-txt','cols':'40','rows':'3'}), label='')
    class Meta:
        model = Comment
        fields = ['body',]

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile
from PIL import Image

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','username','email','password1','password2']


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name','username','email']


class ProfileUpdateForm(forms.ModelForm):
    x = forms.FloatField(widget=forms.HiddenInput(), required=False)
    y = forms.FloatField(widget=forms.HiddenInput(), required=False)
    width = forms.FloatField(widget=forms.HiddenInput(), required=False)
    height = forms.FloatField(widget=forms.HiddenInput(), required=False)

    image = forms.ImageField(label=('Image'), error_messages = {'invalid':("Image files only")}, widget=forms.FileInput, required=False)
    class Meta:
        model = Profile
        fields = ['bio','date_of_birth','image',]


    """Saving Cropped Image"""
    def save(self,*args,**kwargs):
        img = super(ProfileUpdateForm, self).save(*args, **kwargs)

        x = self.cleaned_data.get('x')
        y = self.cleaned_data.get('y')
        w = self.cleaned_data.get('width')
        h = self.cleaned_data.get('height')

        if x and y and w and h:
            image = Image.open(img.image)
            cropped_image = image.crop((x, y, w+x, h+y))
            resized_image = cropped_image.resize((300, 300), Image.ANTIALIAS)
            resized_image.save(img.image.path)

        return img

blog/views.py
from notification.models import Notification
from django.core.checks import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Comment, Post
from .forms import CommentForm
from django.http import HttpResponseRedirect, JsonResponse
from users.models import Profile
from itertools import chain
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.template.loader import render_to_string
import random
from blog.utils import is_ajax


""" Home page with all posts """
def first(request):
    context = {
        'posts':Post.objects.all()
    }
    return render(request, 'blog/first.html', context)

""" Posts of following user profiles """
@login_required
def posts_of_following_profiles(request):

    profile = Profile.objects.get(user = request.user)
    users = [user for user in profile.following.all()]
    posts = []
    qs = None
    for u in users:
        p = Profile.objects.get(user=u)
        p_posts = p.user.post_set.all()
        posts.append(p_posts)
    my_posts = profile.profile_posts()
    posts.append(my_posts)
    if len(posts)>0:
        qs = sorted(chain(*posts), reverse=True, key=lambda obj:obj.date_posted)

    paginator = Paginator(qs, 5)
    page = request.GET.get('page')
    try:
        posts_list = paginator.page(page)
    except PageNotAnInteger:
        posts_list = paginator.page(1)
    except EmptyPage:
        posts_list = paginator.page(paginator.num_pages)
  
    return render(request,'blog/feeds.html',{'profile':profile,'posts':posts_list})


""" Post Like """
@login_required
def LikeView(request):

    post = get_object_or_404(Post, id=request.POST.get('id'))
    liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        liked = False
        notify = Notification.objects.filter(post=post, sender=request.user, notification_type=1)
        notify.delete()
    else:
        post.likes.add(request.user)
        liked = True
        notify = Notification(post=post, sender=request.user, user=post.author, notification_type=1)
        notify.save()

    context = {
        'post':post,
        'total_likes':post.total_likes(),
        'liked':liked,
    }

    if is_ajax(request=request):
        html = render_to_string('blog/like_section.html',context, request=request)
        return JsonResponse({'form':html})


""" Post save """
@login_required
def SaveView(request):

    post = get_object_or_404(Post, id=request.POST.get('id'))
    saved = False
    if post.saves.filter(id=request.user.id).exists():
        post.saves.remove(request.user)
        saved = False
    else:
        post.saves.add(request.user)
        saved = True
    
    context = {
        'post':post,
        'total_saves':post.total_saves(),
        'saved':saved,
    }

    if is_ajax(request=request):
        html = render_to_string('blog/save_section.html',context, request=request)
        return JsonResponse({'form':html})


""" Like post comments """
@login_required
def LikeCommentView(request): # , id1, id2              id1=post.pk id2=reply.pk
    post = get_object_or_404(Comment, id=request.POST.get('id'))
    cliked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        cliked = False
    else:
        post.likes.add(request.user)
        cliked = True

    cpost = get_object_or_404(Post, id=request.POST.get('pid'))
    total_comments2 = cpost.comments.all().order_by('-id')
    total_comments = cpost.comments.all().filter(reply=None).order_by('-id')
    tcl={}
    for cmt in total_comments2:
        total_clikes = cmt.total_clikes()
        cliked = False
        if cmt.likes.filter(id=request.user.id).exists():
            cliked = True

        tcl[cmt.id] = cliked


    context = {
        'comment_form':CommentForm(),
        'post':cpost,
        'comments':total_comments,
        'total_clikes':post.total_clikes(),
        'clikes':tcl
    }

    if is_ajax(request=request):
        html = render_to_string('blog/comments.html',context, request=request)
        return JsonResponse({'form':html})


""" Home page with all posts """
class PostListView(ListView):
    model = Post
    template_name = 'blog/home.html' 
    context_object_name = 'posts'
    ordering = ['-date_posted']
    paginate_by = 5

    def get_context_data(self, *args,**kwargs):
        context = super(PostListView, self).get_context_data()
        users = list(User.objects.exclude(pk=self.request.user.pk))
        if len(users) > 3:
            cnt = 3
        else:
            cnt = len(users)
        random_users = random.sample(users, cnt)
        context['random_users'] = random_users
        return context


""" All the posts of the user """
class UserPostListView(ListView):
    model = Post
    template_name = 'blog/user_posts.html' 
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-date_posted')



""" Post detail view """
def PostDetailView(request,pk):

    stuff = get_object_or_404(Post, id=pk)
    total_likes = stuff.total_likes()
    total_saves = stuff.total_saves()
    total_comments = stuff.comments.all().filter(reply=None).order_by('-id')
    total_comments2 = stuff.comments.all().order_by('-id')

    context = {}

    if request.method == "POST":
        comment_qs = None
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            form = request.POST.get('body')
            reply_id = request.POST.get('comment_id')
            if reply_id:
                comment_qs = Comment.objects.get(id=reply_id)
            
            comment = Comment.objects.create(name=request.user,post=stuff,body=form, reply=comment_qs)
            comment.save()
            if reply_id:
                notify = Notification(post=stuff, sender=request.user, user=stuff.author, text_preview=form, notification_type=4)
                notify.save()
            else:
                notify = Notification(post=stuff, sender=request.user, user=stuff.author, text_preview=form, notification_type=3)
                notify.save()
            total_comments = stuff.comments.all().filter(reply=None).order_by('-id')
            total_comments2 = stuff.comments.all().order_by('-id')
    else:
        comment_form = CommentForm()
             

    tcl={}
    for cmt in total_comments2:
        total_clikes = cmt.total_clikes()
        cliked = False
        if cmt.likes.filter(id=request.user.id).exists():
            cliked = True

        tcl[cmt.id] = cliked
    context["clikes"]=tcl


    liked = False
    if stuff.likes.filter(id=request.user.id).exists():
        liked = True
    context["total_likes"]=total_likes
    context["liked"]=liked


    saved = False
    if stuff.saves.filter(id=request.user.id).exists():
        saved = True
    context["total_saves"]=total_saves
    context["saved"]=saved
    

    context['comment_form'] = comment_form

    context['post']=stuff
    context['comments']=total_comments

    if is_ajax(request=request):
        html = render_to_string('blog/comments.html',context, request=request)
        return JsonResponse({'form':html})

    return render(request, 'blog/post_detail.html', context)


""" Create post """
class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    fields =['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



""" Update post """
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields =['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


""" Delete post """
class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


""" About page """
def about(request):
    return render(request, 'blog/about.html', {'title':'About'})


""" Search by post title or username """
def search(request):
    query = request.GET['query']
    if len(query) >= 150 or len(query) < 1:
        allposts = Post.objects.none()
    elif len(query.strip()) == 0:
        allposts = Post.objects.none()
    else:
        allpostsTitle = Post.objects.filter(title__icontains=query)
        allpostsAuthor = Post.objects.filter(author__username = query)
        allposts = allpostsAuthor.union(allpostsTitle)
    
    params = {'allposts': allposts}
    return render(request, 'blog/search_results.html', params)


""" Liked posts """
@login_required
def AllLikeView(request):
    user = request.user
    liked_posts = user.blogpost.all()
    context = {
        'liked_posts':liked_posts
    }
    return render(request, 'blog/liked_posts.html', context)


""" Saved posts """
@login_required
def AllSaveView(request):
    user = request.user
    saved_posts = user.blogsave.all()
    context = {
        'saved_posts':saved_posts
    }
    return render(request, 'blog/saved_posts.html', context)

notification/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.http import HttpResponse
from notification.models import Notification

# Create your views here.

""" All notifications """
@login_required
def ShowNotifications(request):
    user = request.user
    notifications = Notification.objects.filter(user=user).order_by('-date')
    context = {
        'notifications':notifications,
    }
    return render(request, 'blog/notifications.html', context)

blog/templates/blog/about.html
{% extends "blog/base.html" %} {% block title %} About {% endblock %} 
{% block content %}

<div class="col-md-8 m-auto">
  <div class="content-section">
    <h1>About page</h1>
    <br />
    <p>Made with &#128150; by Rahul Trivedi as a practice project &#9996;</p>
  </div>
</div>

{% endblock %}

blog/templates/blog/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
      integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css"
      integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA=="
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.css"
      integrity="sha512-iAcZ4OrGhQ7KDqtM+LMc+iuv63aJ9O7hPyWBzCXsrZYuhJ6jhdeh40+hf9o4QmZVu8QrH/cWy/JTmoKNOL4Urw=="
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'blog/main.css' %}" />
    <title>FriendsBook | {% block title %}{% endblock %}</title>
  </head>
  <body>
    <header class="site-header">
      <!-- NAVBAR -->
      {% include 'blog/navbar.html' %}
    </header>

    <!-- MAIN SECTION -->
    <main role="main" class="container">
      <div class="row">
        <!-- MESSAGES -->
        <div class="col-md-8 m-auto">
          {% if messages %} {% for message in messages %}
          <div class="alert {{ message.tags }}">{{message}}</div>
          {% endfor %} {% endif %}
        </div>

        {% block content %}{% endblock %}
      </div>
    </main>

    <!-- SCRIPTS -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.min.js"
      integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
      integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"
      integrity="sha512-E+gDQcIvNXE60SjCS38ysf1mGh4ObBpKcUOp0oEaHQHQAdaN2p7GelOpgEdpTuCLoIJyLkNXiqFZbyD9Ak/Ygw=="
      crossorigin="anonymous"
    ></script>

    <script>
      $(function () {
        /* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
        $('#id_image').change(function () {
          if (this.files && this.files[0]) {
            var reader = new FileReader();
            reader.onload = function (e) {
              $('#image').attr('src', e.target.result);
              $('#modalCrop').modal('show');
            };
            reader.readAsDataURL(this.files[0]);
          }
        });

        /* SCRIPTS TO HANDLE THE CROPPER BOX */
        var $image = $('#image');
        var cropBoxData;
        var canvasData;
        $('#modalCrop')
          .on('shown.bs.modal', function () {
            $image.cropper({
              viewMode: 1,
              aspectRatio: 1 / 1,
              minCropBoxWidth: 200,
              minCropBoxHeight: 200,
              ready: function () {
                $image.cropper('setCanvasData', canvasData);
                $image.cropper('setCropBoxData', cropBoxData);
              },
            });
          })
          .on('hidden.bs.modal', function () {
            cropBoxData = $image.cropper('getCropBoxData');
            canvasData = $image.cropper('getCanvasData');
            $image.cropper('destroy');
            location.reload();
          });

        $('.js-zoom-in').click(function () {
          $image.cropper('zoom', 0.1);
        });

        $('.js-zoom-out').click(function () {
          $image.cropper('zoom', -0.1);
        });

        /* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
        $('.js-crop-and-upload').click(function () {
          var cropData = $image.cropper('getData');
          // console.log(cropData);
          $('#id_x').val(cropData['x']);
          $('#id_y').val(cropData['y']);
          $('#id_height').val(cropData['height']);
          $('#id_width').val(cropData['width']);
          $('#formUpload').submit();
        });
      });
    </script>

    <script type="text/javascript">
      $(document).ready(function (event) {
        // $("#chat-box").scrollTop($("#chat-box")[0].scrollHeight);

        // LIKE POSTS

        $(document).on('click', '#like', function (event) {
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "post-like" %}',
            data: { id: pk, csrfmiddlewaretoken: '{{ csrf_token }}' },
            dataType: 'json',
            success: function (response) {
              $('#like-section').html(response['form']);
              console.log($('#like-section').html(response['form']));
            },
            error: function (rs, e) {
              console.log(rs.responseText);
            },
          });
        });

        // COMMENT LIKE

        $(document).on('click', '.clike', function (event) {
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: "{% url 'comment-like' %}",
            data: {
              id: pk,
              pid: '{{post.pk}}',
              csrfmiddlewaretoken: '{{ csrf_token }}',
            },
            dataType: 'json',
            success: function (response) {
              $('.main-comment-section').html(response['form']);
              console.log($('.main-comment-section').html(response['form']));
            },
            error: function (rs, e) {
              console.log(rs.responseText);
            },
          });
        });

        // SAVE POSTS

        $(document).on('click', '#save', function (event) {
          event.preventDefault();
          var pk = $(this).attr('value');
          $.ajax({
            type: 'POST',
            url: '{% url "post-save" %}',
            data: { id: pk, csrfmiddlewaretoken: '{{ csrf_token }}' },
            dataType: 'json',
            success: function (response) {
              $('#save-section').html(response['form']);
              console.log($('#save-section').html(response['form']));
            },
            error: function (rs, e) {
              console.log(rs.responseText);
            },
          });
        });

        // COMMENT FORM

        $(document).on('submit', '.comment-form', function (event) {
          event.preventDefault();
          console.log($(this).serialize());
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function (response) {
              $('.main-comment-section').html(response['form']);
              console.log(response['form']);
              $('textarea').val('');
            },
            error: function (rs, e) {
              console.log(rs.responseText);
            },
          });
        });

        // REPLY FORM

        $(document).on('submit', '.reply-form', function (event) {
          event.preventDefault();
          console.log($(this).serialize());
          $.ajax({
            type: 'POST',
            url: $(this).attr('action'),
            data: $(this).serialize(),
            dataType: 'json',
            success: function (response) {
              $('.main-comment-section').html(response['form']);
              console.log(response['form']);
              $('textarea').val('');
            },
            error: function (rs, e) {
              console.log(rs.responseText);
            },
          });
        });
      });
    </script>

    {% block script %}{% endblock %}
  </body>
</html>

blog/templates/blog/first.html
{% extends "blog/base.html" %}

{% block title %}Home{% endblock %}

{% block content %}

<!-- ADDITIONAL STYLING -->

<style>
  body{
    background-color: #fff;
  }
</style>

<div>
    
    <!-- Page Hero-->
    <section class=" page-header page-header-light bg-white mt-4 container">
      <div class="page-header-content pt-5">
          <div class="container">
              <div class="row align-items-center">
                  <div class="col-lg-6 " data-aos="fade-up">
                      <h1 style="" class="page-header-title font-weight-bold">Let’s Wow your online presence</h1>
                      <br>
                      <p class="page-header-text mb-5">
                        Surround yourself with people who are going to lift you higher. Join today and share your thoughts.
                        <br><br>
                        Designed and developed by <a target="_blank" href="https://github.com/maverickGuyRahul">Rahul Trivedi</a>
                      </p>

                      {% if user.is_authenticated %}
                        <a class="btn btn-lg btn-primary font-weight-bold mr-2 rounded-pill px-4 py-2" href="{% url 'posts-follow-view' %}">Get Started</a>
                        <a class="btn btn-lg btn-primary-soft text-primary font-weight-bold" href="#"><i class="far fa-check-circle"></i>&nbsp;LOGGED IN</a>
                      {% else %}
                        <a class="btn btn-lg btn-primary font-weight-bold mr-2 rounded-pill px-4 py-2" href="{% url 'register' %}">REGISTER</a>
                        <a class="btn btn-lg btn-primary-soft text-primary font-weight-bold" href="{% url 'account_login' %}">LOGIN</a>
                      {% endif %}
                  </div>
                  <div class="col-lg-6 d-none d-lg-block" data-aos="fade-up" data-aos-delay="100"><img class="img-fluid" src="/static/blog/images/undraw_social_interaction_cy9i.png" /></div>
              </div>
          </div>
      </div>
      <br>
    </section>

</div>

{% endblock %}

blog/templates/blog/notifications.html
{% extends "blog/base.html" %}
{% load humanize %}

{% block title %}Notifications{% endblock %}

{% block content %}

{% if notifications|length == 0 %}
    <span class="content-section container">No Notifications</span>
{% endif %}

<div class="col-md-8 m-auto">


{% for notification in notifications %}
    <div class="card">
        <div class="card-body">
            <img class="rounded-circle article-img" src="{{notification.sender.profile.image.url}}" alt="image">
            <span class="card-title h4"><a href="{% url 'profile-detail-view' notification.sender.id %}" >{{notification.sender}}</a></span>
            <span class="text-muted float-right small">{{notification.date|naturaltime}}</span>
            <br><br>
            {% if notification.notification_type == 1 %}
                <p class="card-text"><i class="far fa-thumbs-up"></i>&nbsp;&nbsp;Liked your post "<a href="{% url 'post-detail' notification.post.id %}" >{{notification.post}}</a>"</p>
            {% elif notification.notification_type == 2 %}
                <p class="card-text"><i class="fas fa-user-friends"></i>&nbsp;&nbsp;Started following you</p>
            {% elif notification.notification_type == 3 %}
                <p class="card-text"><i class="far fa-comment-dots"></i>&nbsp;&nbsp;Commented "{{notification.text_preview}}" on your post "<a href="{% url 'post-detail' notification.post.id %}" >{{notification.post}}</a>"</p>
            {% elif notification.notification_type == 4 %}
                <p class="card-text"><i class="fas fa-reply"></i>&nbsp;&nbsp;Replied "{{notification.text_preview}}" to a comment on your post "<a href="{% url 'post-detail' notification.post.id %}" >{{notification.post}}</a>"</p>
            {% endif %}
        </div>
    </div>
    <br>
{% endfor %}

<br><br>

</div>


{% endblock %}